---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-remote-closedown-data
  namespace: mb7pne
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-remote-closedown
  namespace: mb7pne
  labels:
    app.kubernetes.io/name: matrix-remote-closedown
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-remote-closedown
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matrix-remote-closedown
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: matrix-remote-closedown
          image: ghcr.io/dannixon/matrix-remote-closedown:6f339e2d5da815c82b9f48d1e7c5290f7016acce
          livenessProbe:
            httpGet:
              path: /alive
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: RUST_LOG
              value: info
          envFrom:
            - secretRef:
                name: closedown-secrets
          args:
            - "--station-name=mb7pne"
            - "--mqtt-broker=tcp://mqtt.mqtt.svc.cluster.local:1883"
            - "--mqtt-username=matrix_remote_closedown"
            - "--status-topic=mb7pne/remote_closedown/status"
            - "--command-topic=mb7pne/remote_closedown/command"
            - "--matrix-storage=/data/matrix"
            - "--matrix-username=@izayoi_sakuya:matrix.org"
            - "--room=!LpBfhDcZLlKVvDoNKV:matrix.org"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matrix-remote-closedown-data
