---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: power-off-overnight
  namespace: mb7pne
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mqtt-msg-send
              image: docker.io/library/eclipse-mosquitto:2.0.15
              envFrom:
                - secretRef:
                    name: closedown-secrets
              command:
                - /usr/bin/mosquitto_pub
                - -u
                - matrix_remote_closedown
                - -P
                - "$(MQTT_PASSWORD)"
                - -h
                - mqtt.mqtt.svc.cluster.local
                - -t
                - mb7pne/remote_closedown/command
                - -m
                - '{"enable_tx_power": false}'
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: power-on-in-morning
  namespace: mb7pne
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mqtt-msg-send
              image: docker.io/library/eclipse-mosquitto:2.0.15
              envFrom:
                - secretRef:
                    name: closedown-secrets
              command:
                - /usr/bin/mosquitto_pub
                - -u
                - matrix_remote_closedown
                - -P
                - "$(MQTT_PASSWORD)"
                - -h
                - mqtt.mqtt.svc.cluster.local
                - -t
                - mb7pne/remote_closedown/command
                - -m
                - '{"enable_tx_power": true}'
          restartPolicy: OnFailure
