---
- name: Deploy
  hosts: localhost

  tasks:
    - name: Set secrets
      ansible.builtin.set_fact:
        mqtt_secrets: "{{ lookup('community.general.passwordstore', 'ansible_secrets/public_infra/mqtt_passwords returnall=true') | from_yaml }}"

    - name: Ensure Grafana Helm repository is available
      run_once: true
      delegate_to: localhost
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts
        state: present

    # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
    - name: Ensure Grafana is deployed
      run_once: true
      delegate_to: localhost
      kubernetes.core.helm:
        update_repo_cache: true
        name: grafana
        namespace: grafana
        create_namespace: true
        chart_ref: grafana/grafana
        chart_version: 6.48.0
        release_values:
          adminUser: dan
          adminPassword: "{{ lookup('community.general.passwordstore', 'Passwords/Personal/cloud_grafana') }}"
          persistence:
            enabled: true
            size: 2Gi
          grafana.ini:
            feature_toggles:
              publicDashboards: true
        state: present

    - name: Ensure deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('template', '%s' % item) | from_yaml_all | list }}"
        state: present
      loop:
        - mqtt.yml
        - influxdb.yml
        - telegraf-makerspace-sensors.yml
        - telegraf-urban-observatory.yml
        - grafana.yml
        - matrix-dapnet-bot.yml
        - spaceapi.yml
        - mb7pne.yml
