---
- name: Grafana Cloud
  hosts: localhost

  pre_tasks:
    - name: Set secrets
      ansible.builtin.set_fact:
        grafana_agent_secrets: "{{ lookup('community.general.passwordstore', 'ansible_secrets/grafana_cloud/personal-projects-prod-1 returnall=true') | from_yaml }}"  # noqa: yaml

  roles:
    - dannixon.k8s.grafana_agent
