---
- name: Traefik
  hosts: localhost

  tasks:
    - name: Ensure Helm repositories are available
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: https://helm.traefik.io/traefik
        state: present

    - name: Ensure Traefik is deployed
      kubernetes.core.helm:
        update_repo_cache: true
        name: traefik
        namespace: traefik
        create_namespace: true
        chart_ref: traefik/traefik
        release_values:
          logs:
            general:
              level: INFO
          ports:
            traefik:
              port: 9000
              protocol: TCP
              expose: false
            web:
              port: 8000
              protocol: TCP
              expose: true
              exposedPort: 80
            websecure:
              port: 8443
              protocol: TCP
              expose: true
              exposedPort: 443
            mqtt:
              port: 1883
              protocol: TCP
              expose: true
              exposedPort: 1883
          certResolvers:
            makerspace-letsencrypt:
              email: dan+makerspace@dan-nixon.com
              storage: /tmp/acme.json
              httpChallenge:
                entryPoint: web
          # additionalArguments:
          #   - --entrypoints.web.http.redirections.entrypoint.to=:443
          #   - --entrypoints.web.http.redirections.entrypoint.scheme=https
          #   - --entrypoints.web.http.redirections.entrypoint.permanent=true
        state: present
