---
apiVersion: v1
kind: Secret
metadata:
  name: admin-user
  namespace: influxdb
stringData:
  password: "ref+sops://src/secrets.yml#/influxdb/admin/password"
  token: "ref+sops://src/secrets.yml#/influxdb/admin/token"
