---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: telegraf-makerspace-sensors
  labels:
    app.kubernetes.io/name: telegraf
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
    spec:
      containers:
        - name: telegraf
          image: docker.io/library/telegraf:1.25.0
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/
      volumes:
        - name: config
          secret:
            secretName: telegraf-config
