---
apiVersion: v1
kind: Secret
metadata:
  name: message-debug-secret
  namespace: mqtt
stringData:
  MQTT_PASSWORD: "ref+sops://src/secrets.yml#/passwords/debug"

---
apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-config
  namespace: mqtt
stringData:
  mosquitto.conf: |
    per_listener_settings false

    log_dest stdout
    log_type all

    allow_anonymous false
    password_file /mosquitto/config/passwd

    persistence false

    listener 1883
    protocol mqtt

  passwd: "ref+sops://src/secrets.yml#/passwd"
