#
# This is a generated file!
#

---
apiVersion: v1
kind: Secret
metadata:
  name: passwords
  namespace: spaceapi-matrix-bot
stringData:
  MQTT_PASSWORD: "ref+sops://src/secrets.yml#/mqtt/password"
  MATRIX_PASSWORD: "ref+sops://src/secrets.yml#/matrix/password"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix
  namespace: spaceapi-matrix-bot
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makerspace-spaceapi-matrix-bot
  namespace: spaceapi-matrix-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: makerspace-spaceapi-matrix-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: makerspace-spaceapi-matrix-bot
    spec:
      containers:
        - name: makerspace-spaceapi-matrix-bot
          image: ghcr.io/dannixon/spaceapi-matrix-bot:9f3894ebb4e20a2e60fb84ff3d9db9d106cb331a
          env:
            - name: RUST_LOG
              value: info
          envFrom:
            - secretRef:
                name: passwords
          args:
            - "--matrix-username"
            - "@makerspace:matrix.org"
            - "--matrix-storage"
            - "/matrix_data"
            - "--spaceapi-url"
            - "http://makerspace-spaceapi.spaceapi.svc.cluster.local:8080"
            - "--mqtt-broker"
            - "tcp://mqtt.mqtt.svc.cluster.local:1883"
            - "--mqtt-username"
            - "spaceapi"
            - "--open-announcement-room"
            - "!rpeYYqBpSAZzhiPZRw:matrix.org"  # (#makerspace-ncl-main:matrix.org)
          volumeMounts:
            - mountPath: /matrix_data
              name: matrix-data
      volumes:
        - name: matrix-data
          persistentVolumeClaim:
            claimName: matrix
---
apiVersion: v1
kind: Namespace
metadata:
  name: spaceapi-matrix-bot
