#
# This is a generated file!
#

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-remote-closedown-data
  namespace: mb7pne
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-remote-closedown
  namespace: mb7pne
  labels:
    app.kubernetes.io/name: matrix-remote-closedown
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-remote-closedown
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matrix-remote-closedown
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: matrix-remote-closedown
          image: ghcr.io/dannixon/matrix-remote-closedown:f7199585332a54dd56e4e9a5aa48d871c5270e33
          livenessProbe:
            httpGet:
              path: /alive
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: RUST_LOG
              value: info
          envFrom:
            - secretRef:
                name: closedown-secrets
          args:
            - "--station-name=mb7pne"
            - "--mqtt-broker=tcp://mqtt.mqtt.svc.cluster.local:1883"
            - "--mqtt-username=matrix_remote_closedown"
            - "--status-topic=mb7pne/remote_closedown/status"
            - "--command-topic=mb7pne/remote_closedown/command"
            - "--matrix-username=@izayoi_sakuya:matrix.org"
            - "--room=!LpBfhDcZLlKVvDoNKV:matrix.org"
            - "--operator=@dannixon:matrix.org"
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matrix-remote-closedown-data
---
apiVersion: v1
kind: Namespace
metadata:
  name: mb7pne
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: power-off-overnight
  namespace: mb7pne
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mqtt-msg-send
              image: docker.io/library/eclipse-mosquitto:2.0.15
              envFrom:
                - secretRef:
                    name: closedown-secrets
              command:
                - /usr/bin/mosquitto_pub
                - -u
                - matrix_remote_closedown
                - -P
                - "$(MQTT_PASSWORD)"
                - -h
                - mqtt.mqtt.svc.cluster.local
                - -t
                - mb7pne/remote_closedown/command
                - -m
                - '{"enable_tx_power": false}'
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: power-on-in-morning
  namespace: mb7pne
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mqtt-msg-send
              image: docker.io/library/eclipse-mosquitto:2.0.15
              envFrom:
                - secretRef:
                    name: closedown-secrets
              command:
                - /usr/bin/mosquitto_pub
                - -u
                - matrix_remote_closedown
                - -P
                - "$(MQTT_PASSWORD)"
                - -h
                - mqtt.mqtt.svc.cluster.local
                - -t
                - mb7pne/remote_closedown/command
                - -m
                - '{"enable_tx_power": true}'
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Secret
metadata:
  name: closedown-secrets
  namespace: mb7pne
stringData:
  MQTT_PASSWORD: "ref+sops://src/secrets.yml#/mqtt/password"
  MATRIX_PASSWORD: "ref+sops://src/secrets.yml#/matrix/password"
