#
# This is a generated file!
#

---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-config
  namespace: telegraf-makerspace-sensors
stringData:
  telegraf.conf: |
    [agent]
    debug = true
    omit_hostname = true

    [[outputs.influxdb_v2]]
    urls = ["http://influxdb.influxdb.svc.cluster.local:8086"]
    token = "ref+sops://src/secrets.yml#/influxdb/token"
    organization = "Maker Space"
    bucket = "sensors"

    [[inputs.mqtt_consumer]]
    servers = ["tcp://mqtt.mqtt.svc.cluster.local:1883"]
    connection_timeout = "10s"
    username = "telegraf"
    password = "ref+sops://src/secrets.yml#/mqtt/password"

    topics = [
      "makerspace/sensors/+/temperature",
      "makerspace/sensors/+/humidity",
    ]
    qos = 0

    data_format = "value"
    data_type = "float"

    [[inputs.mqtt_consumer.topic_parsing]]
    topic = "makerspace/sensors/+/+"
    measurement = "_/_/_/measurement"
    tags = "_/_/sensor/_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: telegraf-makerspace-sensors
  labels:
    app.kubernetes.io/name: telegraf
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: telegraf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telegraf
    spec:
      containers:
        - name: telegraf
          image: docker.io/library/telegraf:1.25.0
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/
      volumes:
        - name: config
          secret:
            secretName: telegraf-config
---
apiVersion: v1
kind: Namespace
metadata:
  name: telegraf-makerspace-sensors
