---
apiVersion: v1
kind: Namespace
metadata:
  name: influxdb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: influxdb
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: influxdb
  labels:
    app.kubernetes.io/name: influxdb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
    spec:
      containers:
        - name: influxdb
          image: docker.io/library/influxdb:2.5.1
          ports:
            - name: influxdb-http
              containerPort: 8086
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-data
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
spec:
  selector:
    app.kubernetes.io/name: influxdb
  ports:
    - port: 8086
      protocol: TCP
      targetPort: influxdb-http

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-https
  namespace: influxdb
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`influxdb.dan-nixon.com`)
      services:
        - Kind: Service
          name: influxdb
          port: 8086
  tls:
    certResolver: letsencrypt
