---
apiVersion: v1
kind: Namespace
metadata:
  name: matrix-dapnet-bot

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dapnet-config
  namespace: matrix-dapnet-bot
data:
  config.toml: |
    [[operators]]
    matrix_ids = ["@dannixon:matrix.org"]
    callsigns = ["M0NXN"]
    dapnet_usernames = ["m0nxn"]

    [[users]]
    matrix_ids = ["@dannixon:matrix.org"]
    callsigns = ["M0NXN"]
    dapnet_usernames = ["m0nxn"]

    [[users]]
    matrix_ids = ["@malcolm:synapse.windmill.onl"]
    callsigns = ["M0VNA"]
    dapnet_usernames = ["m0vna"]

    [[users]]
    matrix_ids = ["@alistair_uk:matrix.org"]
    callsigns = ["M3ZNE"]
    dapnet_usernames = ["m3zne"]

    [[users]]
    matrix_ids = ["@davidmpye:matrix.org"]
    callsigns = ["M0DMP"]

    [[users]]
    matrix_ids = ["@woody:jpd.me.uk"]
    callsigns = ["M7TDM"]

---
apiVersion: v1
kind: Secret
metadata:
  name: passwords
  namespace: matrix-dapnet-bot
data:
  dapnet: "{{ lookup('community.general.passwordstore', 'Passwords/Personal/dapnet/Password') | b64encode }}"
  matrix: "{{ lookup('community.general.passwordstore', 'Passwords/Personal/matrix.org/dapnet/password') | b64encode }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-dapnet-bot
  namespace: matrix-dapnet-bot
  labels:
    app.kubernetes.io/name: matrix-dapnet-bot
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-dapnet-bot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matrix-dapnet-bot
      annotations:
        prometheus.io/scrape: "true"
    spec:
      volumes:
        - name: dapnet-config
          configMap:
            name: dapnet-config
      containers:
        - name: bot
          image: ghcr.io/dannixon/matrix-dapnet-bot:fee1215ea1c10872fce2f2ce41d6c05f65d35b30
          livenessProbe:
            httpGet:
              path: /alive
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: RUST_LOG
              value: debug
            - name: DAPNET_USERNAME
              value: m0nxn
            - name: DAPNET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: dapnet
            - name: MATRIX_USERNAME
              value: "@dapnet:matrix.org"
            - name: MATRIX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: matrix
          volumeMounts:
            - name: dapnet-config
              mountPath: /config
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
