---
apiVersion: v1
kind: Namespace
metadata:
  name: spaceapi

---
apiVersion: v1
kind: Secret
metadata:
  name: spaceapi-mqtt-password
  namespace: spaceapi
stringData:
  MQTT_PASSWORD: "{{ mqtt_secrets.mqtt_passwords.spaceapi }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: makerspace-spaceapi
  namespace: spaceapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: makerspace-spaceapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: makerspace-spaceapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
        - name: makerspace-spaceapi
          image: ghcr.io/dannixon/makerspace-spaceapi:ebc4b934b8279977bdcbf4d8344cc273a9278f77
          livenessProbe:
            httpGet:
              path: /alive
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: RUST_LOG
              value: info
          envFrom:
            - secretRef:
                name: spaceapi-mqtt-password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: makerspace-spaceapi
  namespace: spaceapi
spec:
  selector:
    app.kubernetes.io/name: makerspace-spaceapi
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: makerspace-spaceapi-cors-header
  namespace: spaceapi
spec:
  headers:
    customResponseHeaders:
      Access-Control-Allow-Origin: "*"

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: makerspace-spaceapi-http
  namespace: spaceapi
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`spaceapi.makerspace.org.uk`)
      middlewares:
        - name: makerspace-spaceapi-cors-header
      services:
        - Kind: Service
          name: makerspace-spaceapi
          port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: makerspace-spaceapi-https
  namespace: spaceapi
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`spaceapi.makerspace.org.uk`)
      middlewares:
        - name: makerspace-spaceapi-cors-header
      services:
        - Kind: Service
          name: makerspace-spaceapi
          port: 8080
  tls:
    certResolver: letsencrypt
