# https://github.com/prometheus-community/helm-charts/tree/prometheus-15.17.0/charts/prometheus

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false

  remoteWrite:
    - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
      basic_auth:
        username: "ref+sops://src/secrets.yml#/prometheus/username"
        password: "ref+sops://src/secrets.yml#/prometheus/password"

      write_relabel_configs:
        - source_labels:
            - __name__
          regex: "up|traefik_.*|spaceapi_.*|matrixdapnetbot_.*|matrixremoteclosedown_.*"
          action: keep
        - target_label: cluster
          replacement: personal-projects-2
